[package]
name = "flow-rectpack"
version = "0.2.2"
edition = "2024"
authors = ["Andreas Widen <aw@luflow.net>"]
description = "flow-rectpack is a library for packing rectangles into two-dimensional finite bins."
license = "Zlib"
homepage = "https://luflow.net/"
repository = "https://github.com/hfsoulz/flow-rectpack.git"
readme = "README.md"
keywords = ["rect", "rectangles", "bin", "packing"]
exclude = [".github", ".forgejo", ".gitignore"]

[dependencies]
